### ISSUE TITLE
Professional Training

### ISSUE THREAD

**Issue by AdiraSlat** [cmho/solace-theme#10]
Mac, Chrome and Windows 10, Chrome
If you open the Professional Training Merit description to edit or specify the advantage, it does not let the user scroll up or down, therefore not allowing them to save the advantage.
![screen shot 2019-01-31 at 4 33 27 pm](https://user-images.githubusercontent.com/16806155/52090149-21814780-2576-11e9-8233-81a2090f6dce.png)

**Comment by AdiraSlat** [comment]
Status also has this bug

**Comment by cmho** [comment]
Set bottom property on modal and overflow: auto

**Comment by AdiraSlat** [comment]
Issue still ocuring for user. Affects at least Lee Initiation, Professional Training, and Status

**Comment by AdiraSlat** [comment]
Issue still occurring. Windows 10, chrome
