### ISSUE TITLE
Difficult to read flash notifications

### ISSUE THREAD

**Issue by korey-enright** [cmho/solace-theme#12]
<img width="1286" alt="screen shot 2019-01-31 at 4 56 00 pm" src="https://user-images.githubusercontent.com/10061697/52091303-943ff200-2579-11e9-9de5-c4c8dc6ad797.png">

1. Go to "Create Account" page
2. Input valid account info
3. click on create account

(Possible relevant information, I did not check the "send credentials by email" box)

**Comment by cmho** [comment]
Updated flash message styles for wppb plugin.
