### ISSUE TITLE
Specifying Merits

### ISSUE THREAD

**Issue by AdiraSlat** [cmho/solace-theme#13]
Mac, Chrome
When filling out the text fields of certain merit pop ups, the text is not visible.

I wrote "Larceny" into the field below.
![screen shot 2019-01-31 at 7 33 43 pm](https://user-images.githubusercontent.com/16806155/52097154-433af880-258f-11e9-9f1e-d552e727f388.png)

**Comment by AdiraSlat** [comment]
This only applies to "Specification" and not "Description"

**Comment by cmho** [comment]
Fixed color of form input text in modals by changing it to grey.
