### ISSUE TITLE
Edit Button

### ISSUE THREAD

**Issue by AdiraSlat** [cmho/solace-theme#14]
Mac, Chrome
When clicking "Edit" from the Characters menu, it does not successfully take you to .../character/character-name/edit and instead directs the user to .../character/character-name/
![screen shot 2019-01-31 at 7 38 35 pm](https://user-images.githubusercontent.com/16806155/52097284-15a27f00-2590-11e9-8111-8d3085b1b7ae.png)

**Comment by AdiraSlat** [comment]
Appending /edit to the url also does not take the user to an edit page

**Comment by cmho** [comment]
Value to check against whether sheet is in progress was incorrect; changed from "In Progress" to "in_progress"; should now work.

**Comment by AdiraSlat** [comment]
This issue still occurs. Windows 10, Chrome
