### ISSUE TITLE
Merits and Questionnaire not saving

### ISSUE THREAD

**Issue by AdiraSlat** [cmho/solace-theme#15]
Mac, Chrome
When saving a character, merits and Questionnaire text does not appear to be saved, while dots entered into stats and skills are.
![screen shot 2019-01-31 at 7 43 26 pm](https://user-images.githubusercontent.com/16806155/52097412-995c6b80-2590-11e9-9146-cd7ac869be57.png)

**Comment by AdiraSlat** [comment]
Screen shot of lack of Questionnaire answers
![screen shot 2019-01-31 at 7 45 25 pm](https://user-images.githubusercontent.com/16806155/52097470-c7da4680-2590-11e9-8478-c5672c94840c.png)

**Comment by AdiraSlat** [comment]
Character should have "Iron Skin oo" and "Test" entered in the first question answer.

**Comment by cmho** [comment]
Update: Questionnaire answers should now save correctly. Continuing to investigate issue with saving merits.

**Comment by cmho** [comment]
Merit values should now save; switched to using update_field method from advanced custom fields rather than trying to put everything in via meta_inputs.
