### ISSUE TITLE
Social skill values not saving

### ISSUE THREAD

**Issue by korey-enright** [cmho/solace-theme#17]
Create a character, give em some socials. Save, then:

<img width="513" alt="screen shot 2019-01-31 at 8 24 51 pm" src="https://user-images.githubusercontent.com/10061697/52098879-66b57180-2596-11e9-8087-d67130c90ae2.png">
(Mac, Firefox)

**Comment by cmho** [comment]
Whoops, forgot to add the social skills to the big list of values to save.
