### ISSUE TITLE
When saving new merits and/or modifying them, some merits are replaced with the character name

### ISSUE THREAD

**Issue by korey-enright** [cmho/solace-theme#18]
<img width="388" alt="screen shot 2019-02-01 at 1 15 19 am" src="https://user-images.githubusercontent.com/10061697/52108313-1ef71000-25bf-11e9-996c-525389be96e4.png">

I'm going to be entirely honest, I have no idea how this happened.
Context:
I was playing around with the character sheets, and encountered some weird stuff.
This was with a character who I was editing, not created new, and I got to the edit page by directly going to the character edit page rather than following a link.
There were a number of merits present on the sheet already. Upon adding in specifications and descriptions, some of the merits were replaced with the character name, "Derek Colt." Clicking the Edit button on the ghost merit produced this screen:

<img width="794" alt="screen shot 2019-02-01 at 1 20 52 am" src="https://user-images.githubusercontent.com/10061697/52108434-a5135680-25bf-11e9-801a-2d3fdbb63d9c.png">

I can delete the merit, and it disappears from the Edit page during that session, but reappears on save.

**Comment by sublimemarch** [comment]
This also happened to me, including the strange popup on edit. _However_, I hadn't added any merits to the character yet. This appeared after I first saved it with no merits.

**Comment by thejessleigh** [comment]
This is happening only in the editing screen. Correct merit names are populated after I hit "Save Character"

Also seeing "NAN Remaining" for merits.

http://screen.ac/d4215b8a02e9

**Comment by cmho** [comment]
Merits should no longer lose data and be replaced with junk data; those that are currently displaying incorrectly should be deleted and re-added, sorry!  Also figured out the issue with junk extra merits showing up when a character had taken professional training or an initiation; the method I was using the count the total number of merits for bookkeeping reasons was also counting list items from sub-lists.
