### ISSUE TITLE
Cannot add specialties

### ISSUE THREAD

**Issue by korey-enright** [cmho/solace-theme#19]
When trying to add a specialty, it appears to do nothing. Nothing shows up on the edit page after clicking add, however on save it looks like there is a phantom specialty.
When loading up the edit page again after saving, the phantom specialty does show up, and can be deleted. However it cannot be made to reflect the values of the specialty fields in the form.
<img width="492" alt="screen shot 2019-02-01 at 1 23 55 am" src="https://user-images.githubusercontent.com/10061697/52108578-14894600-25c0-11e9-9e89-4c2114ea3573.png">

<img width="503" alt="screen shot 2019-02-01 at 1 24 20 am" src="https://user-images.githubusercontent.com/10061697/52108632-38e52280-25c0-11e9-9452-870796fbcace.png">

However, when a new edit session is created, and an Academics specialty is given a specification, it will add, unless you have moved to a different skill in the select element's option list and then returned to Academics.

<img width="522" alt="screen shot 2019-02-01 at 1 24 45 am" src="https://user-images.githubusercontent.com/10061697/52108635-3aaee600-25c0-11e9-95f7-29f95fc515ed.png">

**Comment by cmho** [comment]
@korey-enright I'm having trouble replicating this—can you tell me what browser you were using?

**Comment by korey-enright** [comment]
@cmho I'm using the Firefox Developer Edition browser on a Mac

**Comment by korey-enright** [comment]
![screen shot 2019-02-01 at 4 49 13 pm](https://user-images.githubusercontent.com/10061697/52153870-54dcd880-2641-11e9-8930-bb0c9a92e135.png)

It looks like "$" is undefined, which is impacting the onclick listener? Also, when I looked at the DOM, when I selected any skill, no option had the selected attribute added, and when I typed into the input box, no value attribute was added to that element either. Though if it's relying on jQuery at all I think it might all be traceable to the same problem

**Comment by cmho** [comment]
I don’t think it’s jquery—$ isn’t accessible from console because of the way the Wordpress Sage framework manages script dependencies (it’s in a namespaced enclosure iirc), but there would be bigger problems if it wasn’t working at all. I’ll keep investigating.

**Comment by sublimemarch** [comment]
I'm not able to replicate this. I'm using non-developer Firefox.

**Comment by korey-enright** [comment]
OK I figured it out! I can indeed add specialties. The reason why I thought I couldn't is that the clickable area of the add button for whatever reason is only the leftmost third of the button.

**Comment by cmho** [comment]
Ahaha, yeah, I figured out that due to not flex-wrapping the row, despite the fact that i put flex-shrink on the text field, the button is sitting under the next column for some reason??? anyway i’m going to fix it soon hopefully :upside_down:

**Comment by cmho** [comment]
Fixed!
