### ISSUE TITLE
Willpower track calculated by resolve + composure

### ISSUE THREAD

**Issue by korey-enright** [cmho/solace-theme#20]
I'm pretty certain you're already aware of the issue, I just wanted to record it for idk bookkeeping purposes.
<img width="330" alt="screen shot 2019-02-01 at 1 27 42 am" src="https://user-images.githubusercontent.com/10061697/52108779-bad54b80-25c0-11e9-9421-e1ce69615cd6.png">

**Comment by cmho** [comment]
...oh fuck i forgot it's different now. Ahaha, thanks for catching that.

**Comment by cmho** [comment]
Updated calculation to calculate willpower as 5+resolve instead of resolve+composure
