### ISSUE TITLE
Redirect player to characters list on login

### ISSUE THREAD

**Issue by sublimemarch** [cmho/solace-theme#21]
Currently, after I log in, I'm shown this page:

<img width="1554" alt="image" src="https://user-images.githubusercontent.com/9502152/52155216-42fe3400-2647-11e9-825b-279a92aed535.png">

Ideally, I'd like to be automatically redirected to the character dashboard, instead of this page.

**Comment by cmho** [comment]
added redirect_url parameter to WPPB login shortcode; should now redirect to character dashboard post-login.
