### ISSUE TITLE
Can't see Questionnaire answers on show page

### ISSUE THREAD

**Issue by korey-enright** [cmho/solace-theme#24]
<img width="1278" alt="screen shot 2019-02-03 at 2 22 40 pm" src="https://user-images.githubusercontent.com/10061697/52182103-2edd4280-27bf-11e9-8d65-a686d1f4dd41.png">
<img width="1316" alt="screen shot 2019-02-03 at 2 22 28 pm" src="https://user-images.githubusercontent.com/10061697/52182104-2edd4280-27bf-11e9-9da8-19d6eb2f4412.png">

Although I changed to questionnaire answer from what it is in the screenshot to see if maybe the characters were causing something weird, on save the Questionnaire section still appears blank. The answer is however saved, and viewable upon going to the edit page.

**Comment by cmho** [comment]
Ok, so it turns out that if you don't enter any content in a field, get_field_object doesn't return anything for it, so I added some code to initialize the questionnaire fields with a string containing a single space if there's no content.
