### ISSUE TITLE
Refreshing page now clears out attributes & skills but still tracks points like they're still inputted

### ISSUE THREAD

**Issue by isajanusz** [cmho/solace-theme#29]
Earlier today I tried refreshing the page after picking attributes and skills, and the page kept them entered when I did so. Now, it clears them, but when I re-enter them, it starts to show negative points left. When I refresh again, it clears them again and at that point, the negative points don't keep going down as I add more attributes and skills, they just ...still remain negative, but I can't determine how they are increasing/decreasing, sorry I can't be more helpful there! The photos are after one refresh; I had entered an acceptable number of attributes before refresh and then tried to enter more in, and got the negatives shown. For skills, I did select a ton of mental and smaller ton of physical, and the negative values shown here were what I got before refreshing. 
![screen shot 2019-03-03 at 10 36 03 pm](https://user-images.githubusercontent.com/26777208/53711336-4da71700-3e07-11e9-9000-bde75efd7a8b.png)
![screen shot 2019-03-03 at 10 42 22 pm](https://user-images.githubusercontent.com/26777208/53711338-4f70da80-3e07-11e9-8deb-6ea936068e9d.png)

Here's attributes after another refresh, and then not touching anything:
![screen shot 2019-03-03 at 10 40 56 pm](https://user-images.githubusercontent.com/26777208/53711347-5e578d00-3e07-11e9-8f7c-e3052086fded.png)

**Comment by cmho** [comment]
It seems that the browser keeps the hidden input field value between refreshes. I added some scripting to have the browser trigger the click action on the dot corresponding to the value of the field on page load, so it should never have this mismatch again.
