### ISSUE TITLE
div at the end of everyone's character blurbs

### ISSUE THREAD

**Issue by isajanusz** [cmho/solace-theme#35]
This div is at the end of character blurbs:

![Screen Shot 2019-03-24 at 5 42 07 PM](https://user-images.githubusercontent.com/26777208/54887012-35ea0e00-4e5c-11e9-9159-da1e27a0e454.png)
![Screen Shot 2019-03-24 at 5 42 25 PM](https://user-images.githubusercontent.com/26777208/54887013-371b3b00-4e5c-11e9-8788-01382cd0d1f4.png)
![Screen Shot 2019-03-24 at 5 42 13 PM](https://user-images.githubusercontent.com/26777208/54887014-38e4fe80-4e5c-11e9-9e41-4b659cb5b5cf.png)

**Comment by cmho** [comment]
fixed!
