### ISSUE TITLE
Merit modal placement on progressive web app

### ISSUE THREAD

**Issue by sublimemarch** [cmho/solace-theme#36]
Device: Samsung Galaxy S8
Browser: Firefox

Modal needs padding-top added.

**Comment by sublimemarch** [comment]
Specifically, I see this bug when I open my Mind of a Monster merit

**Comment by sublimemarch** [comment]
Also happens with Professional Training

**Comment by sublimemarch** [comment]
And also Contacts

**Comment by cmho** [comment]
tadaaaah done
