### ISSUE TITLE
Links in Descriptions of Merits

### ISSUE THREAD

**Issue by AdiraSlat** [cmho/solace-theme#8]
Mac, Chrome
When viewing the descriptions of merits on the new character page after they have been added, the hyperlinks within the description are not visible.
![screen shot 2019-01-31 at 4 25 52 pm](https://user-images.githubusercontent.com/16806155/52089824-31e4f280-2575-11e9-93f8-50771a4ec506.png)
https://solacelarp.com/new-character/

**Comment by cmho** [comment]
Updated link color inside modal to same grey color as text.
