### ISSUE TITLE
Following Description Links

### ISSUE THREAD

**Issue by AdiraSlat** [cmho/solace-theme#9]
Mac, Chrome
When following the link within a Merit Description of an newly created and unsaved character, it reloads your tab onto the destination page. This clears everything you have entered into the mechanics of the character
![screen shot 2019-01-31 at 4 30 00 pm](https://user-images.githubusercontent.com/16806155/52089985-a029b500-2575-11e9-87c0-1df93e302dac.png)
After following link, and hitting back button
![screen shot 2019-01-31 at 4 30 51 pm](https://user-images.githubusercontent.com/16806155/52089989-a3bd3c00-2575-11e9-9b6e-a974eec36f6f.png)
If you navigate to the character tab afterwards, nothing shows.
![screen shot 2019-01-31 at 4 32 21 pm](https://user-images.githubusercontent.com/16806155/52090037-cea79000-2575-11e9-809a-aacf5399681c.png)

**Comment by AdiraSlat** [comment]
Perhaps it should open the link in a new tab instead?

**Comment by cmho** [comment]
Updated javascript to add `rel="external" target="_blank"` to links loaded into modals.
